name = "starship"
version = "1.24.2"
license = "ISC"
homepage = "https://github.com/starship/starship"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "3f12f61883ff324c1dbe7b885fa125d5490960e5cad6a12eeaa34695ec1b5744"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "starship"
path = "starship"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-aarch64-unknown-linux-musl.tar.gz"
sha256 = "56b9ff412bbf374d29b99e5ac09a849124cb37a0a13121e8470df32de53c1ea6"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "starship"
path = "starship"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-x86_64-apple-darwin.tar.gz"
sha256 = "237beb10cc970c4361536e9f9f434dfed755f8282c5cd951b6a7e3fcbda8e779"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "starship"
path = "starship"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-aarch64-apple-darwin.tar.gz"
sha256 = "d3a0da21374962625a2ee992110979bc1fa33424d7b6aea58a70405e26544fd9"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "starship"
path = "starship"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/starship/starship/releases/download/v1.24.2/starship-x86_64-pc-windows-msvc.zip"
sha256 = "d38424c595320e9639a276666347d5e44cb004de3972f40b9a5a1a6b88537f29"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "starship"
path = "starship.exe"
