name = "jq"
version = "1.8.1"
license = "MIT"
homepage = "https://github.com/jqlang/jq"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://raw.githubusercontent.com/spiritledsoftware/crosspack-registry/main/artifacts/jq/jq-1.8.1-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "5e486ffa036a9399d669b3941966c75aaca9da2792e8e6cc48fd29ab23674031"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "jq"
path = "bin/jq"
