name = "gh"
version = "2.87.3"
license = "MIT"
homepage = "https://github.com/cli/cli"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/cli/cli/releases/download/v2.87.3/gh_2.87.3_linux_amd64.tar.gz"
sha256 = "c6e5537631fca45f277ef405ce8751d139b491e9402cc20891a003525a8773b2"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "gh"
path = "bin/gh"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/cli/cli/releases/download/v2.87.3/gh_2.87.3_linux_arm64.tar.gz"
sha256 = "5f5d89563bf26751e2173b37e594065504e85b6b781c1f1832d24bf2c2b4554f"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "gh"
path = "bin/gh"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/cli/cli/releases/download/v2.87.3/gh_2.87.3_macOS_amd64.zip"
sha256 = "7b8d5495fe9689494b1c69559c0d28209bc057bb028008e903ec4b3e19bd8c75"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "gh"
path = "bin/gh"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/cli/cli/releases/download/v2.87.3/gh_2.87.3_macOS_arm64.zip"
sha256 = "dedfc6f569e9dbc5b92d47dce44acadbdf5b6b7a861510db0c748dfac55002f6"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "gh"
path = "bin/gh"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/cli/cli/releases/download/v2.87.3/gh_2.87.3_windows_amd64.zip"
sha256 = "c590bcb488f80a85c8febd5cde27edd68fdd481bd004aaf9adc50dcf1b21c09c"
archive = "zip"
strip_components = 1

[[artifacts.binaries]]
name = "gh"
path = "bin/gh.exe"
