name = "ripgrep"
version = "15.1.0"
license = "MIT OR Unlicense"
homepage = "https://github.com/BurntSushi/ripgrep"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz"
sha256 = "1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "rg"
path = "rg"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "2b661c6ef508e902f388e9098d9c4c5aca72c87b55922d94abdba830b4dc885e"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "rg"
path = "rg"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-apple-darwin.tar.gz"
sha256 = "64811cb24e77cac3057d6c40b63ac9becf9082eedd54ca411b475b755d334882"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "rg"
path = "rg"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"
sha256 = "378e973289176ca0c6054054ee7f631a065874a352bf43f0fa60ef079b6ba715"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "rg"
path = "rg"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-pc-windows-msvc.zip"
sha256 = "124510b94b6baa3380d051fdf4650eaa80a302c876d611e9dba0b2e18d87493a"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "rg"
path = "rg.exe"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-pc-windows-msvc.zip"
sha256 = "00d931fb5237c9696ca49308818edb76d8eb6fc132761cb2a1bd616b2df02f8e"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "rg"
path = "rg.exe"
