name = "ripgrep"
version = "15.1.0"
license = "MIT OR Unlicense"
homepage = "https://github.com/BurntSushi/ripgrep"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz"
sha256 = "1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "rg"
path = "rg"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz"
sha256 = "362c6f8e80a6891178e4f9f5439dad8f50cc8794f5344dc91cd13b9f591ca630"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "rg"
path = "rg"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-pc-windows-msvc.zip"
sha256 = "d6e6e5bb7e1f89fa8fd2f31e7f0f3ed67f85eca085f35f308cb69448afac2e8b"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "rg"
path = "rg.exe"
