name = "ripgrep"
version = "15.1.0"
license = "MIT OR Unlicense"
homepage = "https://github.com/BurntSushi/ripgrep"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz"
sha256 = "1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "rg"
path = "rg"
