name = "fd"
version = "10.3.0"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/sharkdp/fd"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "c3c2bc79f838e780173fc8f18b337ec273e7ba17c7ff8f551be29fc3c19b7916"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "fd"
path = "fd"
[[artifacts.completions]]
shell = "bash"
path = "autocomplete/fd.bash"

[[artifacts.completions]]
shell = "zsh"
path = "autocomplete/_fd"

[[artifacts.completions]]
shell = "fish"
path = "autocomplete/fd.fish"

[[artifacts.completions]]
shell = "powershell"
path = "autocomplete/fd.ps1"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "66f297e404400a3358e9a0c0b2f3f4725956e7e4435427a9ae56e22adbe73a68"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "fd"
path = "fd"
[[artifacts.completions]]
shell = "bash"
path = "autocomplete/fd.bash"

[[artifacts.completions]]
shell = "zsh"
path = "autocomplete/_fd"

[[artifacts.completions]]
shell = "fish"
path = "autocomplete/fd.fish"

[[artifacts.completions]]
shell = "powershell"
path = "autocomplete/fd.ps1"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-x86_64-apple-darwin.tar.gz"
sha256 = "50d30f13fe3d5914b14c4fff5abcbd4d0cdab4b855970a6956f4f006c17117a3"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "fd"
path = "fd"
[[artifacts.completions]]
shell = "bash"
path = "autocomplete/fd.bash"

[[artifacts.completions]]
shell = "zsh"
path = "autocomplete/_fd"

[[artifacts.completions]]
shell = "fish"
path = "autocomplete/fd.fish"

[[artifacts.completions]]
shell = "powershell"
path = "autocomplete/fd.ps1"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-aarch64-apple-darwin.tar.gz"
sha256 = "0570263812089120bc2a5d84f9e65cd0c25e4a4d724c80075c357239c74ae904"
archive = "tar.gz"
strip_components = 1

[[artifacts.binaries]]
name = "fd"
path = "fd"
[[artifacts.completions]]
shell = "bash"
path = "autocomplete/fd.bash"

[[artifacts.completions]]
shell = "zsh"
path = "autocomplete/_fd"

[[artifacts.completions]]
shell = "fish"
path = "autocomplete/fd.fish"

[[artifacts.completions]]
shell = "powershell"
path = "autocomplete/fd.ps1"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-x86_64-pc-windows-msvc.zip"
sha256 = "318aa2a6fa664325933e81fda60d523fff29444129e91ebf0726b5b3bcd8b059"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "fd"
path = "fd.exe"
[[artifacts.completions]]
shell = "bash"
path = "autocomplete/fd.bash"

[[artifacts.completions]]
shell = "zsh"
path = "autocomplete/_fd"

[[artifacts.completions]]
shell = "fish"
path = "autocomplete/fd.fish"

[[artifacts.completions]]
shell = "powershell"
path = "autocomplete/fd.ps1"

[[artifacts]]
target = "aarch64-pc-windows-msvc"
url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-aarch64-pc-windows-msvc.zip"
sha256 = "bf9b1e31bcac71c1e95d49c56f0d872f525b95d03854e94b1d4dd6786f825cc5"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "fd"
path = "fd.exe"
[[artifacts.completions]]
shell = "bash"
path = "autocomplete/fd.bash"

[[artifacts.completions]]
shell = "zsh"
path = "autocomplete/_fd"

[[artifacts.completions]]
shell = "fish"
path = "autocomplete/fd.fish"

[[artifacts.completions]]
shell = "powershell"
path = "autocomplete/fd.ps1"

