name = "crosspack"
version = "0.0.4"
license = "MIT"
homepage = "https://github.com/spiritledsoftware/crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.0.4/crosspack-v0.0.4-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "751472ba8dbe02490efb37d84c53a7f98812e886177d682a66fab00ec6538702"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.0.4/crosspack-v0.0.4-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "24f3a9b8da30d9fda0c9e429680734d5623b36e7e7824fc8083db96b99bc38f6"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.0.4/crosspack-v0.0.4-x86_64-unknown-linux-musl.tar.gz"
sha256 = "938298b34d121a7ef094434a7051f549372bfc8378c986bc266523ceb6920b00"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.0.4/crosspack-v0.0.4-aarch64-unknown-linux-musl.tar.gz"
sha256 = "6fdef02e276111271fd90abaaee2e53a6088c090edf5974ef22d2976134888e4"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.0.4/crosspack-v0.0.4-x86_64-apple-darwin.tar.gz"
sha256 = "52f3a7a4988a50ada812f1c3debba254ff37a78b6ea4f9acf4088861005be652"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.0.4/crosspack-v0.0.4-aarch64-apple-darwin.tar.gz"
sha256 = "64a7357a9b275d2ef76f46e796193c721f728dd30a61211e2e5062b6ed841d97"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.0.4/crosspack-v0.0.4-x86_64-pc-windows-msvc.zip"
sha256 = "878e55f912d15c26685579c9a36d2bfb6d9e1e43a3d7670302f93cee2b16b647"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack.exe"

[[artifacts.binaries]]
name = "cpk"
path = "crosspack.exe"
