name = "crosspack"
version = "0.7.5"
license = "MIT"
homepage = "https://github.com/spiritledsoftware/crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.5/crosspack-v0.7.5-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "ec4ee745228530d0b81d852ea7d1c90d231e1afc8467dd709ff3ede00f947482"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.5/crosspack-v0.7.5-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "0c5ab910714815799082d761b31df9df8d705e31b63771085a7fdd7863b7a7e2"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.5/crosspack-v0.7.5-x86_64-unknown-linux-musl.tar.gz"
sha256 = "47705f0922e336d98c7ed6d0dce4c4f034c9341150c59c1da7c7a19468df6a2e"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.5/crosspack-v0.7.5-aarch64-unknown-linux-musl.tar.gz"
sha256 = "c6e2ddbf778c845d5c89753a31bfcb37bf4b8f29408a07375da0a02165e53ce4"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.5/crosspack-v0.7.5-x86_64-apple-darwin.tar.gz"
sha256 = "6ac9881626396f21e307a6f1d9c2516312e4a3a2135391a0134387a79d45fcd9"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.5/crosspack-v0.7.5-aarch64-apple-darwin.tar.gz"
sha256 = "45f888829885b49e32351698e8e35703c382999aba8151eb3a6b3514cd34cd63"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.5/crosspack-v0.7.5-x86_64-pc-windows-msvc.zip"
sha256 = "872045c43df02fd136cef8dc038948e59844bf480a9c72a132feefa83ffaf365"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack.exe"

[[artifacts.binaries]]
name = "cpk"
path = "crosspack.exe"
