name = "crosspack"
version = "0.7.4"
license = "MIT"
homepage = "https://github.com/spiritledsoftware/crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.4/crosspack-v0.7.4-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "1449e2ad7459bb0c05e773f5d67429fd0a750c5cea91a74741443bbcfc872952"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.4/crosspack-v0.7.4-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "cc8925218bdd5576ca90c70334afb522a38b220676e99957868e4dc9befd3d59"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.4/crosspack-v0.7.4-x86_64-unknown-linux-musl.tar.gz"
sha256 = "2c63e3ffcbbc1c81822fdf060749da9afcadf4839c4f3346d205a3b06370d696"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.4/crosspack-v0.7.4-aarch64-unknown-linux-musl.tar.gz"
sha256 = "f8dd66988b372512f1c3908d12376421e64e0565078ee276fc048942b22685b5"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.4/crosspack-v0.7.4-x86_64-apple-darwin.tar.gz"
sha256 = "4f0a608da9fb31481a223222cd3def2b6e5f42caebb441c3534c8c5e5baa5673"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.4/crosspack-v0.7.4-aarch64-apple-darwin.tar.gz"
sha256 = "5b25f9a2b2bf3027161adcee97c393962f8cc7c8945631eda78118d9d53eab90"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.4/crosspack-v0.7.4-x86_64-pc-windows-msvc.zip"
sha256 = "4324e4ed0ca534264f02b2816bb45b2b9053d106b756c44d780b232a60de2161"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack.exe"

[[artifacts.binaries]]
name = "cpk"
path = "crosspack.exe"
