name = "crosspack"
version = "0.7.6"
license = "MIT"
homepage = "https://github.com/spiritledsoftware/crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.6/crosspack-v0.7.6-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "9096a840c58eb84d3dca5d156b968a9854c8b022a3e8e0d10219f43e764334a8"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.6/crosspack-v0.7.6-aarch64-unknown-linux-gnu.tar.gz"
sha256 = "0c43efaab88e64b6de81057056a88f478d8997ef521eaeac7af1e72efbcc987e"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.6/crosspack-v0.7.6-x86_64-unknown-linux-musl.tar.gz"
sha256 = "c9f04ca62a7fb258cfa9c8ba55b569b36f0e414c2fb3b7fac50fc8dc6c94e62f"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-unknown-linux-musl"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.6/crosspack-v0.7.6-aarch64-unknown-linux-musl.tar.gz"
sha256 = "a5fc9da42b01763bcc75742838d8d15f9491bc4de79f271316c7569d56d75d14"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.6/crosspack-v0.7.6-x86_64-apple-darwin.tar.gz"
sha256 = "0bd3f6cacecf62479372b8323ff2a14a3fed51cff0b889cc178071a24a95e6f5"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "aarch64-apple-darwin"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.6/crosspack-v0.7.6-aarch64-apple-darwin.tar.gz"
sha256 = "12173369dcd63acc261c46f54063067520ef3cf7855db46eae6039ff59c42e43"
archive = "tar.gz"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack"

[[artifacts]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/spiritledsoftware/crosspack/releases/download/v0.7.6/crosspack-v0.7.6-x86_64-pc-windows-msvc.zip"
sha256 = "9a927619a755c27a1f00903ccb6097271a0f467283fc20812c9f13876b6ecc1f"
archive = "zip"
strip_components = 0

[[artifacts.binaries]]
name = "crosspack"
path = "crosspack.exe"

[[artifacts.binaries]]
name = "cpk"
path = "crosspack.exe"
